### ISSUE TITLE
Mapping volume

### ISSUE THREAD

**Issue by DavidTNguyen** [kns-it/Docker-GitPitch#10]
Hope you can help.  I tried to map the a local drive to the internal container, but not sure how.  I can't find the info in your README.  Here is my docker-compose.yml

`version: '3'
services:
  gitpitch:
    image: knsit/gitpitch:latest

    volumes:
     - ~/dev/mylocalrepo:/repo

    environment:
      - "GP_HOST=localhost"
      - "GP_PORT:9000"
      - "GP_GITHUB_AS_DEFAULT=true"
    ports:
      - 9000:9000`

**Comment by prskr** [comment]
Sorry I completely missed this issue.
I'm sorry but this is not the way GitPitch works. You don't mount the repository into the container but you configure GitPitch to be able to access your VCS provider (e.g. GitHub, GitLab.com, Gitea,...) :wink: 

This works perfectly with public repositories but things are a little bit cumbersome if you try to use a private repository. If that is the case you have multiple options:

* pay for GitPitch Pro (might be worth it, I used it on my own for a few months and was totally satisfied with it!)
* use another tool like my own creation [goveal](/baez90/go-reveal-slides) that applies another approach and is by far not so feature rich like GitPitch (and most likely won't ever be)
* use a completely different approach like e.g. [pandoc](/jgm/pandoc)

Again my apologies for the late answer. I hope I could help you out a bit.
